"""Guards the demo narration pipeline.

The voiceover is generated by parsing ``docs/demo-narration.md`` at render
time, so an innocuous edit to that document can silently change or drop spoken
beats. These tests pin the contract between the prose and the parser.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
NARRATION = REPO_ROOT / "docs" / "demo-narration.md"
DRIVER = REPO_ROOT / "scripts" / "narrate_demo.sh"
ASSEMBLER = REPO_ROOT / "scripts" / "assemble_narration.swift"
MUXER = REPO_ROOT / "scripts" / "narrate_video.swift"

HEADING = re.compile(r"^##\s+(\d+)\s*[·.]\s*(.+?)\s*\((\d+):(\d\d)\s*[–-]", re.MULTILINE)


def _beats() -> list[tuple[int, int]]:
    """Return ``(number, offset_seconds)`` for every narration beat."""
    text = NARRATION.read_text(encoding="utf-8")
    return [
        (int(number), int(minutes) * 60 + int(seconds))
        for number, _title, minutes, seconds in HEADING.findall(text)
    ]


def test_narration_pipeline_scripts_exist() -> None:
    assert NARRATION.is_file()
    assert DRIVER.is_file()
    assert ASSEMBLER.is_file()
    assert MUXER.is_file()


def test_driver_is_executable_and_parses() -> None:
    assert DRIVER.stat().st_mode & 0o111, "narrate_demo.sh must be executable"
    result = subprocess.run(["bash", "-n", str(DRIVER)], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


def test_driver_reads_the_markdown_rather_than_copying_it() -> None:
    driver = DRIVER.read_text(encoding="utf-8")
    assert "docs/demo-narration.md" in driver
    assert "assemble_narration.swift" in driver
    assert "narrate_video.swift" in driver


def test_every_beat_has_spoken_words() -> None:
    """A beat with no blockquote renders silence and desyncs the rest."""
    sections = NARRATION.read_text(encoding="utf-8").split("\n## ")[1:]
    spoken = [s for s in sections if HEADING.match("## " + s)]
    assert spoken, "no narration beats found"
    for section in spoken:
        quoted = [line for line in section.splitlines() if line.startswith(">")]
        assert quoted, f"beat has no spoken lines: {section.splitlines()[0]!r}"


def test_beat_offsets_increase_monotonically() -> None:
    beats = _beats()
    assert len(beats) >= 2
    offsets = [offset for _number, offset in beats]
    assert offsets == sorted(offsets), f"beat timecodes go backwards: {offsets}"
    assert offsets[0] == 0, "the first beat must start at 0:00"


def test_beat_numbers_are_sequential() -> None:
    numbers = [number for number, _offset in _beats()]
    assert numbers == list(range(1, len(numbers) + 1)), numbers


def test_narration_stays_within_a_short_demo() -> None:
    """A demo that opens with a long preamble does not get watched."""
    offsets = [offset for _number, offset in _beats()]
    assert offsets[-1] <= 180, f"last beat starts at {offsets[-1]}s"
