"""Add tenant_id to findings, audit_logs, and connectors.

Revision ID: 0005
Revises:     0004
Create Date: 2026-07-29 00:00:00.000000

Before this revision neither table carried an owner, so the list endpoints
returned every tenant's rows to any authenticated caller. The column is
nullable so existing rows are preserved as-is: a legacy row has no owner and
is therefore visible only to an unscoped admin identity, never to a
tenant-bound one.

Usage:
    alembic upgrade 0005      # add the columns
    alembic downgrade 0004    # drop them
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Revision identifiers — used by Alembic
revision:       str                             = "0005"
down_revision:  Union[str, None]               = "0004"
branch_labels:  Union[str, Sequence[str], None] = None
depends_on:     Union[str, Sequence[str], None] = None


def _drop_global_asset_id_uniqueness() -> None:
    """Remove any single-column uniqueness on ``asset_memory.asset_id``.

    The constraint name is generated by the database, and older deployments
    express it as a unique index rather than a named constraint, so it is
    looked up rather than hard-coded.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    for constraint in inspector.get_unique_constraints("asset_memory"):
        if constraint.get("column_names") == ["asset_id"] and constraint.get("name"):
            op.drop_constraint(constraint["name"], "asset_memory", type_="unique")
            return

    for index in inspector.get_indexes("asset_memory"):
        if index.get("unique") and index.get("column_names") == ["asset_id"] and index.get("name"):
            op.drop_index(index["name"], table_name="asset_memory")
            return


def upgrade() -> None:
    """Add the tenancy column to both globally-readable tables."""
    op.add_column("findings", sa.Column("tenant_id", sa.String(length=128), nullable=True))
    op.create_index("ix_findings_tenant_id", "findings", ["tenant_id"])
    op.add_column("audit_logs", sa.Column("tenant_id", sa.String(length=128), nullable=True))
    op.create_index("ix_audit_logs_tenant_id", "audit_logs", ["tenant_id"])
    op.add_column("connectors", sa.Column("tenant_id", sa.String(length=128), nullable=True))
    op.create_index("ix_connectors_tenant_id", "connectors", ["tenant_id"])

    op.add_column("incident_memory", sa.Column("tenant_id", sa.String(length=128), nullable=True))
    op.create_index("ix_incident_memory_tenant_id", "incident_memory", ["tenant_id"])
    op.add_column("asset_memory", sa.Column("tenant_id", sa.String(length=128), nullable=True))
    op.create_index("ix_asset_memory_tenant_id", "asset_memory", ["tenant_id"])
    # Asset ids are only unique inside a tenant; a global unique constraint
    # would itself leak cross-tenant existence through insert failures.
    #
    # Depending on how the table was created, global uniqueness on asset_id
    # exists either as a UNIQUE constraint or as a unique index, and the
    # generated name differs. Resolve it instead of assuming one shape.
    _drop_global_asset_id_uniqueness()
    op.create_unique_constraint("uq_asset_memory_tenant_asset", "asset_memory", ["tenant_id", "asset_id"])

    op.add_column("swarm_jobs", sa.Column("tenant_id", sa.String(length=128), nullable=True))
    op.create_index("ix_swarm_jobs_tenant_id", "swarm_jobs", ["tenant_id"])


def downgrade() -> None:
    """Remove the tenancy columns."""
    op.drop_index("ix_connectors_tenant_id", table_name="connectors")
    op.drop_column("connectors", "tenant_id")

    op.drop_index("ix_swarm_jobs_tenant_id", table_name="swarm_jobs")
    op.drop_column("swarm_jobs", "tenant_id")
    op.drop_constraint("uq_asset_memory_tenant_asset", "asset_memory", type_="unique")
    op.create_index("ix_asset_memory_asset_id", "asset_memory", ["asset_id"], unique=True)
    op.drop_index("ix_asset_memory_tenant_id", table_name="asset_memory")
    op.drop_column("asset_memory", "tenant_id")
    op.drop_index("ix_incident_memory_tenant_id", table_name="incident_memory")
    op.drop_column("incident_memory", "tenant_id")
    op.drop_index("ix_audit_logs_tenant_id", table_name="audit_logs")
    op.drop_column("audit_logs", "tenant_id")
    op.drop_index("ix_findings_tenant_id", table_name="findings")
    op.drop_column("findings", "tenant_id")
